title: bGZoCg Blog
description: the Whole Words I Wanna Talk With You.
author: bGZoCg
permalink: /:title.html

plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

# markdown: redcarpet
# redcarpet:
#    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
# see more in https://github.com/vmg/redcarpet/blob/master/README.markdown
  
