title: bGZo's Blog
description: Small is Beautiful, Less is More.
author: bGZo
permalink: /:title.html

plugins:
  - jekyll-feed
  - jekyll-sitemap

highlighter: rouge

# markdown: redcarpet
# redcarpet:
#    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
# see more in https://github.com/vmg/redcarpet/blob/master/README.markdown
