name: blog

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 16 * * *'

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run Script
        run: |
          rm -rf _posts/
          python3 sync-issues.py ${{ secrets.G_T }}

      - name: Run Safe Dir
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Push Articles
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name bgzo
            git config user.email bgzocg@outlook.com
            git add .
            git commit -m "Update Articles"
            git push
          else
            echo "no changes";
          fi
