name: blog

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 16 * * *'

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Delete All Old Post
        run: |
          rm -rf _posts/

      - name: Sync issue to repository
        run: |
          python3 utils/sync.py -t ${{ secrets.G_T }} -p bGZo/blog posts thoughts letters

      - name: Proof article
        run: |
          python3 utils/proof.py

      - name: Convert Text to Traditional Chinese
        run: |
          python3 utils/stconverter.py _posts -t

      - name: Run Safe Dir
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Push Articles
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name bgzo
            git config user.email bgzo@outlook.com
            git add .
            git commit -m "Sync article"
            git push
          else
            echo "no changes";
          fi
